In [ ]:
#https://www.youtube.com/watch?v=uL0-6kfiH3g&t=1275s

In [5]:
#Download dataset using kaggle api
import os
os.environ["KAGGLE_API_TOKEN"] = "KGAT_2012d7a832580f3ff1a50a6291afb733"

import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Warning: Looks like you're using an outdated `kaggle`` version (installed: {current_version}), please consider upgrading to the latest version ({latest_version_str})
Warning: Looks like you're using an outdated `kaggle`` version (installed: {current_version}), please consider upgrading to the latest version ({latest_version_str})
Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [6]:
#Extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [7]:
#Data cleaning and transformations using Pandas
import pandas as pd
df = pd.read_csv('orders.csv')
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [8]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [9]:
#handling null values
df = pd.read_csv('orders.csv',na_values = ['Not Available', 'unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [10]:
#renaming column names to all lower case and underscores instead of spaces

#df.rename(columns = {'Order Id' : 'order_id', 'Ship Mode' : 'ship_mode'}.....becomes tough for more columns)

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [11]:
#deriving new columns like discount, sale_price and profit

df['discount'] = df['list_price'] * df['discount_percent'] * 0.01

df['sale_price'] = df['list_price'] - df['discount']

df['profit'] = df['sale_price'] - df['cost_price']

df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [12]:
#dropping unwanted columns

df.drop(columns = ['cost_price','list_price','discount_percent'], inplace = True)

'''inplace = True drops columns from the dataframe, if we dont use it the columns will be dropped only when this 
cell is run that is temporarily'''

'inplace = True drops columns from the dataframe, if we dont use it the columns will be dropped only when this \ncell is run that is temporarily'

In [13]:
#dealing with datatypes

df.dtypes

order_id          int64
order_date       object
ship_mode        object
segment          object
country          object
city             object
state            object
postal_code       int64
region           object
category         object
sub_category     object
product_id       object
quantity          int64
discount        float64
sale_price      float64
profit          float64
dtype: object

In [14]:
#lets convert order_date from object to datetime datatype

df['order_date'] = pd.to_datetime(df['order_date'], format = "%Y-%m-%d")
df.dtypes

order_id                 int64
order_date      datetime64[ns]
ship_mode               object
segment                 object
country                 object
city                    object
state                   object
postal_code              int64
region                  object
category                object
sub_category            object
product_id              object
quantity                 int64
discount               float64
sale_price             float64
profit                 float64
dtype: object

In [2]:
#loading the data to sql server

#!pip install pandas sqlalchemy pymysql

DEPRECATION: Loading egg at /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages/huggingface_hub-0.22.2-py3.8.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Requirement already satisfied: pandas in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (2.2.1)
Requirement already satisfied: sqlalchemy in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (1.4.39)
Requirement already satisfied: pymysql in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (1.1.2)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/vaeshnavireddyalla/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [19]:
from sqlalchemy import create_engine
import urllib.parse

password = urllib.parse.quote_plus("Avr@2001")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/orders_db"
)

In [29]:
df.to_sql(
    name="orders",
    con=engine,
    if_exists="append",
    index=False
) 

''' If we use if_exists = 'replace', the table will be created in sql but with columns taking high memory like 
varchar data types so in order to avoid this we create table in sql using DDL by assigned data types and use 
if_exists = "append" '''

9994

In [21]:
len(df)

9994

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      9994 non-null   int64
 1   order_date    9994 non-null   datetime64[ns]
 2   ship_mode     9988 non-null   object
 3   segment       9994 non-null   object
 4   country       9994 non-null   object
 5   city          9994 non-null   object
 6   state         9994 non-null   object
 7   postal_code   9994 non-null   int64
 8   region        9994 non-null   object
 9   category      9994 non-null   object
 10  sub_category  9994 non-null   object
 11  product_id    9994 non-null   object
 12  quantity      9994 non-null   int64
 13  discount      9994 non-null   float64
 14  sale_price    9994 non-null   float64
 15  profit        9994 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(9)
memory usage: 1.2+ MB